Add a tag to the EFS: Name=ClusterName to allow users to use the EFS easily
aws-quickstart/quickstart-amazon-eks pull request #211
Opened 2020-10-15 11:52 UTC by nandexsp

Use the tag name with the clusterName parameter to allow users to search the EFS and use the ID with EKS to deploy new pvc or sc.

*Issue #, if available:*
When a user try to create more than one EKS-quickstart cluster with EFS is too dificcult to search what is the EFS deployed for that cluster. If an user wants to use the EFS to add new pvcs is necessary to compare the creation dates when with the ClusterName tag will be easily. 

*Description of changes:*
Add a tag into the EFS template called **Name** with the value: **ClusterName**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-16 21:33 UTC, gargana commented
/do_e2e_tests

2020-10-19 15:05 UTC, jaymccon commented
/do-e2e-tests

2020-10-20 18:25 UTC, jaymccon commented
How about using `EksClusterName` as the tag key to make it a bit more clear to those looking at the tag without context ?

2020-10-20 18:41 UTC, nandexsp commented
> How about using `EksClusterName` as the tag key to make it a bit more clear to those looking at the tag without context ?

I think that is the same no?

2020-10-26 20:37 UTC, jaymccon requested changes

2020-10-26 20:37 UTC, jaymccon commented on templates/amazon-eks-efs.template.yaml
> +    Default: "EKS-EFS"
No need for default here

2020-10-26 20:37 UTC, jaymccon commented on templates/amazon-eks-efs.template.yaml
> +        - Key: Name
Rather than `Name` can we use `EKSClusterName`

2020-10-27 16:28 UTC, jaymccon commented
Apologies for the back and forth on this one.

2020-10-27 16:28 UTC, merged