Tigera Calico Intergration
aws-quickstart/quickstart-amazon-eks pull request #237
Opened 2020-11-04 22:02 UTC by troy-ameigh

*Description of changes: Intergrated Tigera Calico Network Policy (Community)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-05 16:36 UTC, troy-ameigh commented
Made an update to fix issue checker found

2020-11-05 18:56 UTC, gargana commented on .gitmodules
> +	url = git@github.com:aws-quickstart/quickstart-eks-tigera-calico.git
Where is the branch that this will map too?

2020-11-05 18:57 UTC, gargana commented on .taskcat.yml
> +      PerAccountSharedResources: "Yes"
This isn't correct for the CI can these be removed?

2020-11-05 19:01 UTC, gargana requested changes
Hi Troy

Some small cosmetic things and something in .taskcat.yml to address.

Otherwise looking good.

Andrew

2020-11-05 19:01 UTC, gargana commented on templates/amazon-eks.template.yaml
> +      Parameters:
Are the other Calico params not required here?

2020-11-06 20:59 UTC, troy-ameigh commented on templates/amazon-eks-entrypoint-existing-vpc.template.yaml
> +        Parameters:
CalicoIntegration is the only needed parameter

2020-11-06 21:01 UTC, troy-ameigh commented on templates/amazon-eks-entrypoint-existing-vpc.template.yaml
> +        Parameters:
Commit 7a0292a  should have cleaned this up

2020-11-06 21:02 UTC, troy-ameigh commented on templates/amazon-eks.template.yaml
> +      Parameters:
No you only need the enablement param

2020-11-06 21:05 UTC, gargana approved these changes

2020-11-06 21:05 UTC, merged